// LapCont — Transport — Real C#/Kotlin nested-TLS interoperability runner
// License: MIT
package com.lapcont.transport
import java.io.File
import java.security.KeyStore
import javax.net.ssl.*
import kotlinx.coroutines.*
import org.json.JSONObject

/** CLI-only test fixture runner. Credentials are generated by the C# host and never bundled in the APK. */
fun main(args: Array<String>) = runBlocking {
    require(args.isNotEmpty()) { "Usage: transport:run --args='<fixture.json> [bad-inner-pin|no-client]'" }
    val config = JSONObject(File(args[0]).readText())
    interoperability(config, args.getOrNull(1))
}

/** Coroutine interoperability fixture. Only tests provision exportable PKCS12 credentials; enrollment is not implemented. */
suspend fun interoperability(config: JSONObject, negative: String? = null, report: (String) -> Unit = ::println) {
    require(negative == null || negative == "bad-inner-pin" || negative == "no-client") { "Unknown negative probe" }
    // Establish a valid baseline first. An offline host or broken outer TLS must not count as identity rejection.
    if (negative != null) interoperability(config, report = report)
    var rejected = false
    try {
        withTimeout(15000) {
            for (channel in listOf("control", "media")) {
                val keyStore = KeyStore.getInstance("PKCS12")
                File(config.getString("client_identity")).inputStream().use { keyStore.load(it, config.getString("password").toCharArray()) }
                val km = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm()).apply { init(keyStore, config.getString("password").toCharArray()) }
                val pin = if (negative == "bad-inner-pin") "0".repeat(64) else config.getString("pc_fingerprint")
                val context = SSLContext.getInstance("TLS").apply { init(if (negative == "no-client") emptyArray() else km.keyManagers, arrayOf(PinTrust(pin)), null) }
                val engine = context.createSSLEngine("localhost", 7443).apply {
                    useClientMode = true; enabledProtocols = arrayOf("TLSv1.3", "TLSv1.2")
                }
                WebSocketCarrier(config.getString("url").replace("/control", "/$channel"), config.getString("pc_fingerprint")).use { carrier ->
                    val tls = TlsEngine(engine, carrier); tls.handshake()
                    val hello = JSONObject(String(tls.readFrame(Frames.CONTROL_LIMIT), Charsets.UTF_8))
                    check(hello.getString("protocol") == "LPC1" && hello.getString("channel") == channel)
                    check(hello.getString("pc_id") == config.getString("pc_id") && hello.getString("phone_id") == config.getString("phone_id"))
                    check(hello.getString("connection_session_id").length == 32)
                    val payload = if (channel == "control") "{\"probe\":\"CSharp-Kotlin-mTLS\",\"params\":{\"value\":42}}".toByteArray()
                        else Frames.encode(MediaFrame(1, 1, ByteArray(16) { it.toByte() }, 42, 33333, Frames.unhex("000000016588")))
                    tls.writeFrame(payload, Frames.MEDIA_LIMIT + 40)
                    check(tls.readFrame(Frames.MEDIA_LIMIT + 40).contentEquals(payload))
                    report("VERIFIED $channel CSharp/Kotlin ${tls.protocol} exact-peer pins, framed echo")
                }
            }
        }
    } catch (e: SSLException) { if (negative == null) throw e; rejected = true }
    catch (e: java.io.IOException) { if (negative == null) throw e; rejected = true }
    catch (e: kotlinx.coroutines.channels.ClosedReceiveChannelException) { if (negative == null) throw e; rejected = true }
    if (negative != null) { check(rejected) { "Wrong identity was accepted" }; report("VERIFIED rejection: $negative") }
}
