// LapCont — Tests — Real WebSocket carrier size, type, EOF and cancellation boundaries
// License: MIT
using System.Net;
using System.Net.WebSockets;
using LapCont.Security;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Hosting.Server;
using Microsoft.AspNetCore.Hosting.Server.Features;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Xunit;

namespace LapCont.Tests;

/// <summary>Uses actual Kestrel/client WebSockets with generated bytes. No capture input or substitute crypto.</summary>
public sealed class CarrierBoundaryTests
{
    [Theory] [InlineData(false)] [InlineData(true)]
    public Task RejectsTextAndOversizedBinaryMessages(bool oversized) => WithSockets(
        async (socket, ct) => await socket.SendAsync(new byte[oversized ? 65537 : 1], oversized ? WebSocketMessageType.Binary : WebSocketMessageType.Text, true, ct),
        async (socket, ct) =>
        {
            await using var carrier = new WebSocketStream(socket);
            await Assert.ThrowsAsync<InvalidDataException>(async () =>
            {
                var buffer = new byte[65536];
                while (await carrier.ReadAsync(buffer, ct) != 0) { }
            });
        });

    [Fact]
    public Task LargeWritesSplitIntoBoundedMessagesWithoutChangingBytes()
    {
        var expected = Enumerable.Range(0, 131195).Select(i => (byte)(i % 251)).ToArray();
        return WithSockets(async (socket, ct) =>
        {
            using var received = new MemoryStream();
            var buffer = new byte[8192]; var messageBytes = 0;
            while (received.Length < expected.Length)
            {
                var result = await socket.ReceiveAsync(buffer.AsMemory(), ct);
                Assert.Equal(WebSocketMessageType.Binary, result.MessageType);
                messageBytes += result.Count; Assert.InRange(messageBytes, 1, 65536);
                received.Write(buffer, 0, result.Count);
                if (result.EndOfMessage) messageBytes = 0;
            }
            Assert.Equal(0, messageBytes); Assert.Equal(expected, received.ToArray());
        }, async (socket, ct) =>
        {
            await using var carrier = new WebSocketStream(socket);
            await carrier.WriteAsync(expected, ct);
        });
    }

    [Fact]
    public Task PeerCloseIsEndOfStream() => WithSockets(
        async (socket, ct) => await socket.CloseOutputAsync(WebSocketCloseStatus.NormalClosure, "finite probe", ct),
        async (socket, ct) =>
        {
            await using var carrier = new WebSocketStream(socket);
            Assert.Equal(0, await carrier.ReadAsync(new byte[1], ct));
        });

    [Fact]
    public Task WaitingReadHonorsCancellation() => WithSockets(async (socket, ct) =>
    {
        try { await socket.ReceiveAsync(new byte[1].AsMemory(), ct); }
        catch (WebSocketException) { /* Expected transport end after the client's cancelled receive. */ }
    }, async (socket, _) =>
    {
        await using var carrier = new WebSocketStream(socket);
        using var deadline = new CancellationTokenSource(TimeSpan.FromMilliseconds(200));
        await Assert.ThrowsAnyAsync<OperationCanceledException>(async () => await carrier.ReadAsync(new byte[1], deadline.Token));
    });

    private static async Task WithSockets(Func<WebSocket, CancellationToken, Task> serverAction,
        Func<ClientWebSocket, CancellationToken, Task> clientAction)
    {
        using var deadline = new CancellationTokenSource(TimeSpan.FromSeconds(10));
        var outcome = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
        var builder = WebApplication.CreateBuilder(Array.Empty<string>()); builder.Logging.ClearProviders();
        builder.WebHost.ConfigureKestrel(options => options.Listen(IPAddress.Loopback, 0));
        await using var app = builder.Build(); app.UseWebSockets();
        app.Map("/carrier", async context =>
        {
            using var socket = await context.WebSockets.AcceptWebSocketAsync();
            try { await serverAction(socket, deadline.Token); outcome.TrySetResult(); }
            catch (Exception error) { outcome.TrySetException(error); }
        });
        await app.StartAsync(deadline.Token);
        try
        {
            var address = app.Services.GetRequiredService<IServer>().Features.Get<IServerAddressesFeature>()!.Addresses.Single();
            using var socket = new ClientWebSocket();
            await socket.ConnectAsync(new Uri(address.Replace("http://", "ws://") + "/carrier"), deadline.Token);
            await clientAction(socket, deadline.Token); await outcome.Task.WaitAsync(deadline.Token);
        }
        finally { await app.StopAsync(CancellationToken.None); }
    }
}
